//! Compose ユニット生成 — KDL `Service`/`Stage` → Compose Spec YAML
//!
//! Podman+Quadlet 追従 epic（creo-memories `mem_1CbD3b6j1s3pxQ1TGvaXtv`）WS4。
//!
//! cloud は Quadlet（WS2/WS3）、demo 環境は Compose という分担。stage が
//! `backend "compose"` を宣言しているとき、KDL から Compose Spec YAML を
//! 生成し `podman compose` に処理させる。
//!
//! YAML 生成は `quadlet.rs` の手書き INI 生成と同じ哲学で手書き（全 scalar を
//! 二重引用符でエスケープ）。`podman compose` / `docker compose` 共通の
//! Compose Spec を出力する。
//!
//! 規約:
//! - compose プロジェクト名・ネットワーク名 = `{project}-{stage}`
//! - `container_name` = `{project}-{stage}-{service}`（fleetflow 命名規約）
//! - attribution は `fleetflow.{project,stage,service}` label
//! - volume の host パスは compose ファイル位置非依存にするため絶対パス化

use std::io;
use std::path::{Path, PathBuf};

use fleetflow_core::{Flow, Protocol, RestartPolicy, Stage};

/// Compose プロジェクト名（`{project}-{stage}`）。
pub fn compose_project_name(project: &str, stage: &str) -> String {
    format!("{project}-{stage}")
}

/// `{project}-{stage}-{service}` 形式のコンテナ名。
fn container_name(project: &str, stage: &str, service: &str) -> String {
    format!("{project}-{stage}-{service}")
}

/// YAML 二重引用符スカラーにエスケープする（純粋関数）。
///
/// `\` `"` に加えて制御文字（LF/CR/TAB 等）もエスケープする。YAML の
/// double-quoted スカラー中の生 LF は空白に folde されるため、エスケープ
/// しないと複数行の値（PEM 証明書・JWT 等）が silent に壊れる。
fn yaml_quote(s: &str) -> String {
    let mut escaped = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            // その他の C0 制御文字は \uXXXX で明示エスケープ
            c if (c as u32) < 0x20 => escaped.push_str(&format!("\\u{:04X}", c as u32)),
            c => escaped.push(c),
        }
    }
    format!("\"{escaped}\"")
}

/// volume の host パスを絶対パスに解決する。
///
/// compose ファイルの配置場所に依存しないよう、相対パスは project_root 基準で
/// 絶対化する（KDL の volume host パスはプロジェクトルート相対）。
fn resolve_host_path(project_root: &Path, host: &Path) -> PathBuf {
    if host.is_absolute() {
        host.to_path_buf()
    } else {
        project_root.join(host)
    }
}

/// `Service`/`Stage` から Compose Spec YAML を生成する（純粋関数）。
///
/// `project_root` は volume host パスの絶対化に使う。静的サイト
/// （`type "static"`）はコンテナではないためスキップする。
pub fn generate_compose_yaml(
    project_root: &Path,
    config: &Flow,
    stage_name: &str,
    stage: &Stage,
) -> anyhow::Result<String> {
    let project = &config.name;
    let compose_name = compose_project_name(project, stage_name);
    let mut out = String::new();

    out.push_str(&format!("# Generated by fleetflow — {compose_name}\n"));
    out.push_str("# DO NOT EDIT — `fleet up` で再生成される\n");
    out.push_str(&format!("name: {}\n", yaml_quote(&compose_name)));
    out.push_str("services:\n");

    for service_name in &stage.services {
        let service = config
            .services
            .get(service_name)
            .ok_or_else(|| anyhow::anyhow!("サービス '{}' の定義が見つかりません", service_name))?;

        // 静的サイトはコンテナではないため Compose 対象外
        if service.is_static() {
            continue;
        }
        let image = service
            .image
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("サービス '{}' に image がありません", service_name))?;

        out.push_str(&format!("  {service_name}:\n"));
        out.push_str(&format!("    image: {}\n", yaml_quote(image)));
        out.push_str(&format!(
            "    container_name: {}\n",
            yaml_quote(&container_name(project, stage_name, service_name))
        ));
        let restart = service.restart.unwrap_or(RestartPolicy::UnlessStopped);
        out.push_str(&format!(
            "    restart: {}\n",
            yaml_quote(restart.as_docker_str())
        ));

        // ポート
        if !service.ports.is_empty() {
            out.push_str("    ports:\n");
            for port in &service.ports {
                let proto = match port.protocol {
                    Protocol::Udp => "/udp",
                    Protocol::Tcp => "",
                };
                let mapping = match &port.host_ip {
                    Some(ip) => format!("{ip}:{}:{}{proto}", port.host, port.container),
                    None => format!("{}:{}{proto}", port.host, port.container),
                };
                out.push_str(&format!("      - {}\n", yaml_quote(&mapping)));
            }
        }

        // 環境変数（決定的出力のためキー順ソート）
        if !service.environment.is_empty() {
            out.push_str("    environment:\n");
            let mut env: Vec<(&String, &String)> = service.environment.iter().collect();
            env.sort_by(|a, b| a.0.cmp(b.0));
            for (key, value) in env {
                out.push_str(&format!("      {key}: {}\n", yaml_quote(value)));
            }
        }

        // ボリューム
        if !service.volumes.is_empty() {
            out.push_str("    volumes:\n");
            for volume in &service.volumes {
                let host = resolve_host_path(project_root, &volume.host);
                let ro = if volume.read_only { ":ro" } else { "" };
                let mapping = format!("{}:{}{ro}", host.display(), volume.container.display());
                out.push_str(&format!("      - {}\n", yaml_quote(&mapping)));
            }
        }

        // 実行コマンド
        if let Some(command) = &service.command {
            out.push_str(&format!("    command: {}\n", yaml_quote(command)));
        }

        // 依存
        if !service.depends_on.is_empty() {
            out.push_str("    depends_on:\n");
            for dep in &service.depends_on {
                out.push_str(&format!("      - {}\n", yaml_quote(dep)));
            }
        }

        // ヘルスチェック
        if let Some(hc) = &service.healthcheck {
            out.push_str("    healthcheck:\n");
            let test: Vec<String> = hc.test.iter().map(|t| yaml_quote(t)).collect();
            out.push_str(&format!("      test: [{}]\n", test.join(", ")));
            out.push_str(&format!(
                "      interval: {}\n",
                yaml_quote(&format!("{}s", hc.interval))
            ));
            out.push_str(&format!(
                "      timeout: {}\n",
                yaml_quote(&format!("{}s", hc.timeout))
            ));
            out.push_str(&format!("      retries: {}\n", hc.retries));
            out.push_str(&format!(
                "      start_period: {}\n",
                yaml_quote(&format!("{}s", hc.start_period))
            ));
        }

        // attribution label
        out.push_str("    labels:\n");
        out.push_str(&format!(
            "      fleetflow.project: {}\n",
            yaml_quote(project)
        ));
        out.push_str(&format!(
            "      fleetflow.stage: {}\n",
            yaml_quote(stage_name)
        ));
        out.push_str(&format!(
            "      fleetflow.service: {}\n",
            yaml_quote(service_name)
        ));
    }

    // ネットワーク — default を {project}-{stage} で命名（サービス名 DNS は
    // Compose default network が自動提供）
    out.push_str("networks:\n");
    out.push_str("  default:\n");
    out.push_str(&format!("    name: {}\n", yaml_quote(&compose_name)));

    Ok(out)
}

/// 生成済み compose.yaml の配置先（`{project_root}/.fleetflow/compose.{stage}.generated.yaml`）。
pub fn compose_file_path(project_root: &Path, stage_name: &str) -> PathBuf {
    project_root
        .join(".fleetflow")
        .join(format!("compose.{stage_name}.generated.yaml"))
}

/// compose.yaml を生成してファイルに書き出す。
pub fn write_compose_file(
    project_root: &Path,
    config: &Flow,
    stage_name: &str,
    stage: &Stage,
) -> anyhow::Result<PathBuf> {
    let yaml = generate_compose_yaml(project_root, config, stage_name, stage)?;
    let path = compose_file_path(project_root, stage_name);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, yaml)?;
    Ok(path)
}

/// `podman compose -f <file> -p <project> <args...>` を実行する。
fn run_podman_compose(file: &Path, project: &str, args: &[&str]) -> io::Result<()> {
    let status = std::process::Command::new("podman")
        .arg("compose")
        .arg("-f")
        .arg(file)
        .arg("-p")
        .arg(project)
        .args(args)
        .status()?;
    if status.success() {
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "`podman compose {}` failed (exit {:?})",
            args.join(" "),
            status.code()
        )))
    }
}

/// stage を Compose で起動する（`podman compose up -d`）。
pub fn compose_up(
    project_root: &Path,
    config: &Flow,
    stage_name: &str,
    stage: &Stage,
) -> anyhow::Result<PathBuf> {
    let file = write_compose_file(project_root, config, stage_name, stage)?;
    let project = compose_project_name(&config.name, stage_name);
    run_podman_compose(&file, &project, &["up", "-d"])?;
    Ok(file)
}

/// stage を Compose で停止する（`podman compose down`）。
///
/// `remove` 指定時は `--volumes` も付けてボリュームごと削除する。
pub fn compose_down(
    project_root: &Path,
    config: &Flow,
    stage_name: &str,
    stage: &Stage,
    remove: bool,
) -> anyhow::Result<()> {
    let file = write_compose_file(project_root, config, stage_name, stage)?;
    let project = compose_project_name(&config.name, stage_name);
    let args: &[&str] = if remove {
        &["down", "--volumes"]
    } else {
        &["down"]
    };
    run_podman_compose(&file, &project, args)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use fleetflow_core::{HealthCheck, Port, Service, ServiceType, Volume};
    use std::collections::HashMap;

    fn flow_with(services: Vec<(&str, Service)>, stage_services: Vec<&str>) -> (Flow, Stage) {
        let mut svc_map = HashMap::new();
        for (name, svc) in services {
            svc_map.insert(name.to_string(), svc);
        }
        let stage = Stage {
            services: stage_services.iter().map(|s| s.to_string()).collect(),
            ..Default::default()
        };
        let mut stages = HashMap::new();
        stages.insert("live".to_string(), stage.clone());
        let flow = Flow {
            name: "myapp".to_string(),
            services: svc_map,
            stages,
            providers: HashMap::new(),
            servers: HashMap::new(),
            registry: None,
            variables: HashMap::new(),
            tenant: None,
        };
        (flow, stage)
    }

    fn container_service() -> Service {
        Service {
            image: Some("postgres:16".to_string()),
            ..Service::default()
        }
    }

    #[test]
    fn yaml_quote_escapes_quotes_and_backslashes() {
        assert_eq!(yaml_quote("simple"), "\"simple\"");
        assert_eq!(yaml_quote(r#"a"b"#), r#""a\"b""#);
        assert_eq!(yaml_quote(r"a\b"), r#""a\\b""#);
    }

    #[test]
    fn yaml_quote_escapes_control_chars() {
        // 生 LF は YAML double-quoted で空白に folde される → \n にエスケープ必須
        assert_eq!(yaml_quote("line1\nline2"), r#""line1\nline2""#);
        assert_eq!(yaml_quote("a\tb"), r#""a\tb""#);
        assert_eq!(yaml_quote("a\rb"), r#""a\rb""#);
        // PEM のような複数行値が壊れないこと
        let pem = "-----BEGIN-----\nMIIB\n-----END-----";
        assert_eq!(yaml_quote(pem), r#""-----BEGIN-----\nMIIB\n-----END-----""#);
        // その他 C0 制御文字（NUL 等）は \uXXXX
        let nul = format!("a{}b", char::from_u32(0).unwrap());
        assert_eq!(yaml_quote(&nul), r#""a\u0000b""#);
    }

    #[test]
    fn compose_project_name_is_project_stage() {
        assert_eq!(compose_project_name("myapp", "live"), "myapp-live");
    }

    #[test]
    fn resolve_host_path_absolutizes_relative() {
        let root = Path::new("/proj");
        assert_eq!(
            resolve_host_path(root, Path::new("./data")),
            PathBuf::from("/proj/./data")
        );
        assert_eq!(
            resolve_host_path(root, Path::new("/abs/data")),
            PathBuf::from("/abs/data")
        );
    }

    #[test]
    fn generate_compose_yaml_has_core_structure() {
        let (flow, stage) = flow_with(vec![("db", container_service())], vec!["db"]);
        let yaml = generate_compose_yaml(Path::new("/proj"), &flow, "live", &stage).unwrap();
        assert!(yaml.contains("name: \"myapp-live\""));
        assert!(yaml.contains("services:\n"));
        assert!(yaml.contains("  db:\n"));
        assert!(yaml.contains("    image: \"postgres:16\""));
        assert!(yaml.contains("    container_name: \"myapp-live-db\""));
        assert!(yaml.contains("    restart: \"unless-stopped\""));
        assert!(yaml.contains("      fleetflow.project: \"myapp\""));
        assert!(yaml.contains("networks:\n"));
        assert!(yaml.contains("    name: \"myapp-live\""));
    }

    #[test]
    fn generate_compose_yaml_renders_ports_env_volumes() {
        let mut svc = container_service();
        svc.ports = vec![
            Port {
                host: 8080,
                container: 80,
                protocol: Protocol::Tcp,
                host_ip: None,
            },
            Port {
                host: 53,
                container: 53,
                protocol: Protocol::Udp,
                host_ip: None,
            },
        ];
        svc.environment.insert("B_KEY".into(), "2".into());
        svc.environment.insert("A_KEY".into(), "1".into());
        svc.volumes = vec![Volume {
            host: "./data".into(),
            container: "/data".into(),
            read_only: true,
        }];
        let (flow, stage) = flow_with(vec![("web", svc)], vec!["web"]);
        let yaml = generate_compose_yaml(Path::new("/proj"), &flow, "live", &stage).unwrap();
        assert!(yaml.contains("      - \"8080:80\""));
        assert!(yaml.contains("      - \"53:53/udp\""));
        // env はキー順ソート
        let a = yaml.find("A_KEY").unwrap();
        let b = yaml.find("B_KEY").unwrap();
        assert!(a < b, "env はキー昇順");
        assert!(yaml.contains("      - \"/proj/./data:/data:ro\""));
    }

    #[test]
    fn generate_compose_yaml_renders_healthcheck() {
        let mut svc = container_service();
        svc.healthcheck = Some(HealthCheck {
            test: vec!["CMD-SHELL".into(), "pg_isready".into()],
            interval: 30,
            timeout: 3,
            retries: 5,
            start_period: 10,
        });
        let (flow, stage) = flow_with(vec![("db", svc)], vec!["db"]);
        let yaml = generate_compose_yaml(Path::new("/proj"), &flow, "live", &stage).unwrap();
        assert!(yaml.contains("      test: [\"CMD-SHELL\", \"pg_isready\"]"));
        assert!(yaml.contains("      interval: \"30s\""));
        assert!(yaml.contains("      retries: 5"));
    }

    #[test]
    fn generate_compose_yaml_skips_static_services() {
        let static_svc = Service {
            service_type: Some(ServiceType::Static),
            ..Service::default()
        };
        let (flow, stage) = flow_with(
            vec![("db", container_service()), ("site", static_svc)],
            vec!["db", "site"],
        );
        let yaml = generate_compose_yaml(Path::new("/proj"), &flow, "live", &stage).unwrap();
        assert!(yaml.contains("  db:\n"));
        assert!(!yaml.contains("  site:\n"));
    }

    #[test]
    fn compose_file_path_is_under_dot_fleetflow() {
        let path = compose_file_path(Path::new("/proj"), "live");
        assert_eq!(
            path,
            PathBuf::from("/proj/.fleetflow/compose.live.generated.yaml")
        );
    }
}
