//! Quadlet ユニット生成 — KDL `Service`/`Stage` → Podman Quadlet ファイル
//!
//! Podman+Quadlet 追従 epic（creo-memories `mem_1CbD3b6j1s3pxQ1TGvaXtv`）WS2。
//!
//! Quadlet は systemd 統合の宣言的 container 管理方式: `.container` / `.network`
//! ファイルを `~/.config/containers/systemd/`（rootless）に置くと、
//! `systemctl --user daemon-reload` で systemd `.service` ユニットが生成される。
//!
//! 本モジュールは **純粋関数のみ**（ファイル I/O や systemctl 実行は含まない）。
//! `Service` → `.container` テキスト、project/stage → `.network` テキストを
//! 生成する。適用層（ファイル書き込み + `systemctl --user`）は WS2 Stage 2。
//!
//! 規約（epic 確定済み — fleetstage / object-records 実績から継承）:
//! - rootless Podman、配置先 `~/.config/containers/systemd/`
//! - `.network` + 個別 `.container`（pod 不使用）
//! - 命名 `{project}-{stage}-{service}`（fleetflow コンテナ命名規約）
//! - attribution は `fleetflow.{project,stage,service}` label

use fleetflow_core::{Protocol, RestartPolicy, Service};

/// `{project}-{stage}-{service}` 形式の正準名を組み立てる。
///
/// Quadlet `.container` ファイル名・`ContainerName=`・systemd unit 名の基底。
pub fn unit_base_name(project: &str, stage: &str, service: &str) -> String {
    format!("{project}-{stage}-{service}")
}

/// `.container` Quadlet ファイル名（`{project}-{stage}-{service}.container`）。
pub fn container_file_name(project: &str, stage: &str, service: &str) -> String {
    format!("{}.container", unit_base_name(project, stage, service))
}

/// `.network` Quadlet ファイル名（`{project}-{stage}.network`）。
pub fn network_file_name(project: &str, stage: &str) -> String {
    format!("{project}-{stage}.network")
}

/// RestartPolicy を systemd `[Service] Restart=` の値に変換する。
///
/// systemd には `unless-stopped` が無いため `always` に寄せる
/// （systemd 管理下では「明示停止しない限り再起動」≒ `always`）。
fn systemd_restart(policy: RestartPolicy) -> &'static str {
    match policy {
        RestartPolicy::No => "no",
        RestartPolicy::Always | RestartPolicy::UnlessStopped => "always",
        RestartPolicy::OnFailure => "on-failure",
    }
}

/// HealthCheck の test ベクタを Quadlet `HealthCmd=` 用のシェル文字列にする。
///
/// - `["CMD-SHELL", "curl ..."]` → `curl ...`
/// - `["CMD", "curl", "-f", "url"]` → `curl -f url`
/// - その他 → 全要素を空白結合
fn health_cmd(test: &[String]) -> Option<String> {
    match test.split_first() {
        Some((head, rest)) if head == "CMD-SHELL" || head == "CMD" => {
            if rest.is_empty() {
                None
            } else {
                Some(rest.join(" "))
            }
        }
        Some(_) => Some(test.join(" ")),
        None => None,
    }
}

/// `Service` から Quadlet `.container` ユニットのテキストを生成する（純粋関数）。
///
/// `service` には KDL `service` ブロックの定義、`service_name` は KDL 上の
/// サービス名を渡す。
pub fn generate_container_unit(
    project: &str,
    stage: &str,
    service_name: &str,
    service: &Service,
    depends_on: &[String],
) -> String {
    let base = unit_base_name(project, stage, service_name);
    let mut out = String::new();

    // ── ヘッダ ──
    out.push_str(&format!("# Generated by fleetflow — {base}\n"));
    out.push_str("# DO NOT EDIT — `fleet up` で再生成される\n\n");

    // ── [Unit] ──
    out.push_str("[Unit]\n");
    out.push_str(&format!(
        "Description=fleetflow {project}/{stage}/{service_name}\n"
    ));
    // depends_on → systemd 順序づけ。依存先 .container の生成 service を After/Requires。
    for dep in depends_on {
        let dep_unit = format!("{}.service", unit_base_name(project, stage, dep));
        out.push_str(&format!("After={dep_unit}\n"));
        out.push_str(&format!("Requires={dep_unit}\n"));
    }
    out.push('\n');

    // ── [Container] ──
    out.push_str("[Container]\n");
    out.push_str(&format!("ContainerName={base}\n"));
    if let Some(image) = &service.image {
        out.push_str(&format!("Image={image}\n"));
    }
    out.push_str(&format!("Network={}\n", network_file_name(project, stage)));

    // ポート公開
    for port in &service.ports {
        let proto = match port.protocol {
            Protocol::Udp => "/udp",
            Protocol::Tcp => "",
        };
        match &port.host_ip {
            Some(ip) => out.push_str(&format!(
                "PublishPort={ip}:{}:{}{proto}\n",
                port.host, port.container
            )),
            None => out.push_str(&format!(
                "PublishPort={}:{}{proto}\n",
                port.host, port.container
            )),
        }
    }

    // 環境変数（KDL 上で決定順を保つため BTreeMap でソート）
    let mut env: Vec<(&String, &String)> = service.environment.iter().collect();
    env.sort_by(|a, b| a.0.cmp(b.0));
    for (key, value) in env {
        out.push_str(&format!("Environment={key}={value}\n"));
    }

    // ボリューム
    for volume in &service.volumes {
        let ro = if volume.read_only { ":ro" } else { "" };
        out.push_str(&format!(
            "Volume={}:{}{ro}\n",
            volume.host.display(),
            volume.container.display()
        ));
    }

    // attribution label（observability の inventory_report がこれで紐付ける）
    out.push_str(&format!("Label=fleetflow.project={project}\n"));
    out.push_str(&format!("Label=fleetflow.stage={stage}\n"));
    out.push_str(&format!("Label=fleetflow.service={service_name}\n"));

    // 実行コマンド上書き
    if let Some(command) = &service.command {
        out.push_str(&format!("Exec={command}\n"));
    }

    // ヘルスチェック
    if let Some(hc) = &service.healthcheck
        && let Some(cmd) = health_cmd(&hc.test)
    {
        out.push_str(&format!("HealthCmd={cmd}\n"));
        out.push_str(&format!("HealthInterval={}s\n", hc.interval));
        out.push_str(&format!("HealthTimeout={}s\n", hc.timeout));
        out.push_str(&format!("HealthRetries={}\n", hc.retries));
        out.push_str(&format!("HealthStartPeriod={}s\n", hc.start_period));
    }
    out.push('\n');

    // ── [Service] ──
    let restart = service.restart.unwrap_or(RestartPolicy::UnlessStopped);
    out.push_str("[Service]\n");
    out.push_str(&format!("Restart={}\n", systemd_restart(restart)));
    out.push('\n');

    // ── [Install] ──
    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");

    out
}

/// project/stage から Quadlet `.network` ユニットのテキストを生成する（純粋関数）。
pub fn generate_network_unit(project: &str, stage: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Generated by fleetflow — {project}-{stage}\n"));
    out.push_str("# DO NOT EDIT — `fleet up` で再生成される\n\n");
    out.push_str("[Unit]\n");
    out.push_str(&format!(
        "Description=fleetflow network {project}/{stage}\n\n"
    ));
    out.push_str("[Network]\n");
    out.push_str(&format!("NetworkName={project}-{stage}\n"));
    out.push_str(&format!("Label=fleetflow.project={project}\n"));
    out.push_str(&format!("Label=fleetflow.stage={stage}\n"));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use fleetflow_core::{HealthCheck, Port, Volume};

    fn base_service() -> Service {
        Service {
            image: Some("docker.io/library/postgres:16".to_string()),
            ..Service::default()
        }
    }

    #[test]
    fn unit_naming_follows_project_stage_service() {
        assert_eq!(unit_base_name("myapp", "live", "db"), "myapp-live-db");
        assert_eq!(
            container_file_name("myapp", "live", "db"),
            "myapp-live-db.container"
        );
        assert_eq!(network_file_name("myapp", "live"), "myapp-live.network");
    }

    #[test]
    fn systemd_restart_maps_unless_stopped_to_always() {
        // systemd に unless-stopped は無いので always に寄せる
        assert_eq!(systemd_restart(RestartPolicy::UnlessStopped), "always");
        assert_eq!(systemd_restart(RestartPolicy::Always), "always");
        assert_eq!(systemd_restart(RestartPolicy::OnFailure), "on-failure");
        assert_eq!(systemd_restart(RestartPolicy::No), "no");
    }

    #[test]
    fn health_cmd_unwraps_cmd_shell_and_cmd() {
        assert_eq!(
            health_cmd(&["CMD-SHELL".into(), "curl -f localhost".into()]),
            Some("curl -f localhost".to_string())
        );
        assert_eq!(
            health_cmd(&["CMD".into(), "curl".into(), "-f".into(), "url".into()]),
            Some("curl -f url".to_string())
        );
        assert_eq!(health_cmd(&[]), None);
    }

    #[test]
    fn container_unit_has_required_sections_and_labels() {
        let unit = generate_container_unit("myapp", "live", "db", &base_service(), &[]);
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("[Container]"));
        assert!(unit.contains("[Service]"));
        assert!(unit.contains("[Install]"));
        assert!(unit.contains("ContainerName=myapp-live-db"));
        assert!(unit.contains("Image=docker.io/library/postgres:16"));
        assert!(unit.contains("Network=myapp-live.network"));
        // attribution label — observability が依存
        assert!(unit.contains("Label=fleetflow.project=myapp"));
        assert!(unit.contains("Label=fleetflow.stage=live"));
        assert!(unit.contains("Label=fleetflow.service=db"));
        assert!(unit.contains("WantedBy=default.target"));
    }

    #[test]
    fn container_unit_renders_ports_with_protocol() {
        let mut svc = base_service();
        svc.ports = vec![
            Port {
                host: 8080,
                container: 80,
                protocol: Protocol::Tcp,
                host_ip: None,
            },
            Port {
                host: 53,
                container: 53,
                protocol: Protocol::Udp,
                host_ip: Some("127.0.0.1".to_string()),
            },
        ];
        let unit = generate_container_unit("myapp", "live", "web", &svc, &[]);
        assert!(unit.contains("PublishPort=8080:80\n"));
        assert!(unit.contains("PublishPort=127.0.0.1:53:53/udp\n"));
    }

    #[test]
    fn container_unit_renders_env_volume_command() {
        let mut svc = base_service();
        svc.environment
            .insert("NODE_ENV".into(), "production".into());
        svc.environment.insert("PORT".into(), "3000".into());
        svc.volumes = vec![Volume {
            host: "./data".into(),
            container: "/data".into(),
            read_only: true,
        }];
        svc.command = Some("npm start".into());
        let unit = generate_container_unit("myapp", "live", "api", &svc, &[]);
        // env はキー順にソートされる（決定的出力）
        let port_idx = unit.find("Environment=PORT=3000").unwrap();
        let node_idx = unit.find("Environment=NODE_ENV=production").unwrap();
        assert!(node_idx < port_idx, "env はキー昇順");
        assert!(unit.contains("Volume=./data:/data:ro\n"));
        assert!(unit.contains("Exec=npm start\n"));
    }

    #[test]
    fn container_unit_renders_depends_on_as_systemd_ordering() {
        let unit = generate_container_unit(
            "myapp",
            "live",
            "api",
            &base_service(),
            &["db".to_string(), "redis".to_string()],
        );
        assert!(unit.contains("After=myapp-live-db.service"));
        assert!(unit.contains("Requires=myapp-live-db.service"));
        assert!(unit.contains("After=myapp-live-redis.service"));
    }

    #[test]
    fn container_unit_renders_healthcheck() {
        let mut svc = base_service();
        svc.healthcheck = Some(HealthCheck {
            test: vec!["CMD-SHELL".into(), "pg_isready".into()],
            interval: 30,
            timeout: 3,
            retries: 5,
            start_period: 10,
        });
        let unit = generate_container_unit("myapp", "live", "db", &svc, &[]);
        assert!(unit.contains("HealthCmd=pg_isready\n"));
        assert!(unit.contains("HealthInterval=30s\n"));
        assert!(unit.contains("HealthRetries=5\n"));
    }

    #[test]
    fn network_unit_has_network_section() {
        let unit = generate_network_unit("myapp", "live");
        assert!(unit.contains("[Network]"));
        assert!(unit.contains("NetworkName=myapp-live"));
        assert!(unit.contains("Label=fleetflow.project=myapp"));
    }
}
