//! Quadlet ユニット生成 — KDL `Service`/`Stage` → Podman Quadlet ファイル
//!
//! Podman+Quadlet 追従 epic（creo-memories `mem_1CbD3b6j1s3pxQ1TGvaXtv`）WS2。
//!
//! Quadlet は systemd 統合の宣言的 container 管理方式: `.container` / `.network`
//! ファイルを `~/.config/containers/systemd/`（rootless）に置くと、
//! `systemctl --user daemon-reload` で systemd `.service` ユニットが生成される。
//!
//! 本モジュールは **純粋関数のみ**（ファイル I/O や systemctl 実行は含まない）。
//! `Service` → `.container` テキスト、project/stage → `.network` テキストを
//! 生成する。適用層（ファイル書き込み + `systemctl --user`）は WS2 Stage 2。
//!
//! 規約（epic 確定済み — fleetstage / object-records 実績から継承）:
//! - rootless Podman、配置先 `~/.config/containers/systemd/`
//! - `.network` + 個別 `.container`（pod 不使用）
//! - 命名 `{project}-{stage}-{service}`（fleetflow コンテナ命名規約）
//! - attribution は `fleetflow.{project,stage,service}` label

use std::io;
use std::path::{Path, PathBuf};

use fleetflow_core::{Flow, Protocol, RestartPolicy, Service, Stage};

/// `{project}-{stage}-{service}` 形式の正準名を組み立てる。
///
/// Quadlet `.container` ファイル名・`ContainerName=`・systemd unit 名の基底。
pub fn unit_base_name(project: &str, stage: &str, service: &str) -> String {
    format!("{project}-{stage}-{service}")
}

/// `.container` Quadlet ファイル名（`{project}-{stage}-{service}.container`）。
pub fn container_file_name(project: &str, stage: &str, service: &str) -> String {
    format!("{}.container", unit_base_name(project, stage, service))
}

/// `.network` Quadlet ファイル名（`{project}-{stage}.network`）。
pub fn network_file_name(project: &str, stage: &str) -> String {
    format!("{project}-{stage}.network")
}

/// RestartPolicy を systemd `[Service] Restart=` の値に変換する。
///
/// systemd には `unless-stopped` が無いため `always` に寄せる
/// （systemd 管理下では「明示停止しない限り再起動」≒ `always`）。
fn systemd_restart(policy: RestartPolicy) -> &'static str {
    match policy {
        RestartPolicy::No => "no",
        RestartPolicy::Always | RestartPolicy::UnlessStopped => "always",
        RestartPolicy::OnFailure => "on-failure",
    }
}

/// HealthCheck の test ベクタを Quadlet `HealthCmd=` 用のシェル文字列にする。
///
/// - `["CMD-SHELL", "curl ..."]` → `curl ...`
/// - `["CMD", "curl", "-f", "url"]` → `curl -f url`
/// - その他 → 全要素を空白結合
fn health_cmd(test: &[String]) -> Option<String> {
    match test.split_first() {
        Some((head, rest)) if head == "CMD-SHELL" || head == "CMD" => {
            if rest.is_empty() {
                None
            } else {
                Some(rest.join(" "))
            }
        }
        Some(_) => Some(test.join(" ")),
        None => None,
    }
}

/// `Service` から Quadlet `.container` ユニットのテキストを生成する（純粋関数）。
///
/// `service` には KDL `service` ブロックの定義、`service_name` は KDL 上の
/// サービス名を渡す。
pub fn generate_container_unit(
    project: &str,
    stage: &str,
    service_name: &str,
    service: &Service,
    depends_on: &[String],
) -> String {
    let base = unit_base_name(project, stage, service_name);
    let mut out = String::new();

    // ── ヘッダ ──
    out.push_str(&format!("# Generated by fleetflow — {base}\n"));
    out.push_str("# DO NOT EDIT — `fleet up` で再生成される\n\n");

    // ── [Unit] ──
    out.push_str("[Unit]\n");
    out.push_str(&format!(
        "Description=fleetflow {project}/{stage}/{service_name}\n"
    ));
    // depends_on → systemd 順序づけ。依存先 .container の生成 service を After/Requires。
    for dep in depends_on {
        let dep_unit = format!("{}.service", unit_base_name(project, stage, dep));
        out.push_str(&format!("After={dep_unit}\n"));
        out.push_str(&format!("Requires={dep_unit}\n"));
    }
    out.push('\n');

    // ── [Container] ──
    out.push_str("[Container]\n");
    out.push_str(&format!("ContainerName={base}\n"));
    if let Some(image) = &service.image {
        out.push_str(&format!("Image={image}\n"));
    }
    out.push_str(&format!("Network={}\n", network_file_name(project, stage)));

    // ポート公開
    for port in &service.ports {
        let proto = match port.protocol {
            Protocol::Udp => "/udp",
            Protocol::Tcp => "",
        };
        match &port.host_ip {
            Some(ip) => out.push_str(&format!(
                "PublishPort={ip}:{}:{}{proto}\n",
                port.host, port.container
            )),
            None => out.push_str(&format!(
                "PublishPort={}:{}{proto}\n",
                port.host, port.container
            )),
        }
    }

    // 環境変数（KDL 上で決定順を保つため BTreeMap でソート）
    let mut env: Vec<(&String, &String)> = service.environment.iter().collect();
    env.sort_by(|a, b| a.0.cmp(b.0));
    for (key, value) in env {
        out.push_str(&format!("Environment={key}={value}\n"));
    }

    // ボリューム
    for volume in &service.volumes {
        let ro = if volume.read_only { ":ro" } else { "" };
        out.push_str(&format!(
            "Volume={}:{}{ro}\n",
            volume.host.display(),
            volume.container.display()
        ));
    }

    // attribution label（observability の inventory_report がこれで紐付ける）
    out.push_str(&format!("Label=fleetflow.project={project}\n"));
    out.push_str(&format!("Label=fleetflow.stage={stage}\n"));
    out.push_str(&format!("Label=fleetflow.service={service_name}\n"));

    // 実行コマンド上書き
    if let Some(command) = &service.command {
        out.push_str(&format!("Exec={command}\n"));
    }

    // ヘルスチェック
    if let Some(hc) = &service.healthcheck
        && let Some(cmd) = health_cmd(&hc.test)
    {
        out.push_str(&format!("HealthCmd={cmd}\n"));
        out.push_str(&format!("HealthInterval={}s\n", hc.interval));
        out.push_str(&format!("HealthTimeout={}s\n", hc.timeout));
        out.push_str(&format!("HealthRetries={}\n", hc.retries));
        out.push_str(&format!("HealthStartPeriod={}s\n", hc.start_period));
    }
    out.push('\n');

    // ── [Service] ──
    let restart = service.restart.unwrap_or(RestartPolicy::UnlessStopped);
    out.push_str("[Service]\n");
    out.push_str(&format!("Restart={}\n", systemd_restart(restart)));
    out.push('\n');

    // ── [Install] ──
    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");

    out
}

/// project/stage から Quadlet `.network` ユニットのテキストを生成する（純粋関数）。
pub fn generate_network_unit(project: &str, stage: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Generated by fleetflow — {project}-{stage}\n"));
    out.push_str("# DO NOT EDIT — `fleet up` で再生成される\n\n");
    out.push_str("[Unit]\n");
    out.push_str(&format!(
        "Description=fleetflow network {project}/{stage}\n\n"
    ));
    out.push_str("[Network]\n");
    out.push_str(&format!("NetworkName={project}-{stage}\n"));
    out.push_str(&format!("Label=fleetflow.project={project}\n"));
    out.push_str(&format!("Label=fleetflow.stage={stage}\n"));
    out
}

// ─────────────────────────────────────────────
// 適用層（WS2 Stage 2b）— 生成済みユニットをディスクに反映 + systemctl
// ─────────────────────────────────────────────

/// 生成済み Quadlet ユニット 1 つ（ファイル名 + 内容）。
#[derive(Debug, Clone)]
pub struct QuadletUnit {
    /// ファイル名（`*.container` / `*.network`）。
    pub file_name: String,
    /// ファイル内容。
    pub content: String,
}

/// rootless Quadlet の標準配置ディレクトリ `~/.config/containers/systemd/`。
///
/// `XDG_CONFIG_HOME` → `$HOME/.config` の順で base を解決する。
pub fn default_quadlet_dir() -> Option<PathBuf> {
    let base = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))?;
    Some(base.join("containers/systemd"))
}

/// 指定 project/stage の fleetflow 生成 Quadlet ファイルか判定する（純粋関数）。
///
/// `{project}-{stage}-*.container` または `{project}-{stage}.network` に一致。
/// 他 project/stage・ユーザー手書きファイルは false。
pub fn is_fleetflow_unit(file_name: &str, project: &str, stage: &str) -> bool {
    let container_prefix = format!("{project}-{stage}-");
    (file_name.starts_with(&container_prefix) && file_name.ends_with(".container"))
        || file_name == network_file_name(project, stage)
}

/// project/stage の Quadlet ユニット束を systemd quadlet ディレクトリに反映する。
///
/// snapshot 全置換: 既存の同 project/stage の fleetflow 生成ファイルを削除して
/// から新しい束を書き出す（KDL から消えた service の unit も消える）。
/// 他 project/stage のファイル・ユーザー手書きファイルには触れない。
pub fn sync_quadlet_dir(
    systemd_dir: &Path,
    project: &str,
    stage: &str,
    units: &[QuadletUnit],
) -> io::Result<()> {
    std::fs::create_dir_all(systemd_dir)?;

    // 旧 fleetflow ファイルを削除（snapshot 置換）
    for entry in std::fs::read_dir(systemd_dir)? {
        let entry = entry?;
        if let Some(name) = entry.file_name().to_str()
            && is_fleetflow_unit(name, project, stage)
        {
            std::fs::remove_file(entry.path())?;
        }
    }

    // 新ファイルを書き出し
    for unit in units {
        std::fs::write(systemd_dir.join(&unit.file_name), &unit.content)?;
    }
    Ok(())
}

/// `systemctl --user daemon-reload` — Quadlet generator を再走させ、
/// `.container`/`.network` から systemd `.service` を再生成する。
pub fn systemctl_user_daemon_reload() -> io::Result<()> {
    run_systemctl_user(&["daemon-reload"])
}

/// `systemctl --user start <unit>`。
pub fn systemctl_user_start(unit: &str) -> io::Result<()> {
    run_systemctl_user(&["start", unit])
}

/// `systemctl --user stop <unit>`。
pub fn systemctl_user_stop(unit: &str) -> io::Result<()> {
    run_systemctl_user(&["stop", unit])
}

fn run_systemctl_user(args: &[&str]) -> io::Result<()> {
    let status = std::process::Command::new("systemctl")
        .arg("--user")
        .args(args)
        .status()?;
    if status.success() {
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "`systemctl --user {}` failed (exit {:?})",
            args.join(" "),
            status.code()
        )))
    }
}

// ─────────────────────────────────────────────
// ステージ適用（WS2 Stage 2c / WS3）— CLI・agent 共用の orchestration
// ─────────────────────────────────────────────

/// stage の全 container サービスから Quadlet ユニット束を組み立てる（純粋関数）。
///
/// `.network` 1 つ + container サービスごとの `.container`。静的サイト
/// （`type "static"`）は Quadlet 対象外なのでスキップする。
pub fn build_stage_units(
    config: &Flow,
    stage_name: &str,
    stage: &Stage,
) -> anyhow::Result<Vec<QuadletUnit>> {
    let project = &config.name;
    let mut units = vec![QuadletUnit {
        file_name: network_file_name(project, stage_name),
        content: generate_network_unit(project, stage_name),
    }];

    for service_name in &stage.services {
        let service = config
            .services
            .get(service_name)
            .ok_or_else(|| anyhow::anyhow!("サービス '{}' の定義が見つかりません", service_name))?;

        // 静的サイトはコンテナではないため Quadlet 対象外
        if service.is_static() {
            continue;
        }
        if service.image.is_none() {
            anyhow::bail!("サービス '{}' に image が指定されていません", service_name);
        }

        units.push(QuadletUnit {
            file_name: container_file_name(project, stage_name, service_name),
            content: generate_container_unit(
                project,
                stage_name,
                service_name,
                service,
                &service.depends_on,
            ),
        });
    }

    Ok(units)
}

/// container サービスの systemd unit 名（`{project}-{stage}-{service}.service`）。
pub fn service_units(config: &Flow, stage_name: &str, stage: &Stage) -> Vec<String> {
    stage
        .services
        .iter()
        .filter(|name| {
            config
                .services
                .get(name.as_str())
                .is_some_and(|s| !s.is_static())
        })
        .map(|name| format!("{}.service", unit_base_name(&config.name, stage_name, name)))
        .collect()
}

/// `apply_stage` の結果。
#[derive(Debug, Clone)]
pub struct QuadletApplyOutcome {
    /// disk に書き出したユニットファイル数。
    pub units_written: usize,
    /// `systemctl --user start` した service unit 名。
    pub services_started: Vec<String>,
}

/// stage を Quadlet で実体化する — CLI（`fleet up`）と agent（WS3）の共用経路。
///
/// 1. KDL からユニット束を生成（`build_stage_units`）
/// 2. `~/.config/containers/systemd/` に snapshot 反映（`sync_quadlet_dir`）
/// 3. `systemctl --user daemon-reload` で `.service` を再生成
/// 4. 各 container サービスを `systemctl --user start`
///
/// 注: `systemctl --user` は呼び出しプロセスのユーザーセッションに作用する。
/// rootless Quadlet のため、呼び出し元（CLI なら実行ユーザー、agent なら
/// agent プロセス）が対象の rootless ユーザーである必要がある（provisioning は WS5）。
pub fn apply_stage(
    config: &Flow,
    stage_name: &str,
    stage: &Stage,
) -> anyhow::Result<QuadletApplyOutcome> {
    let units = build_stage_units(config, stage_name, stage)?;
    let dir = default_quadlet_dir()
        .ok_or_else(|| anyhow::anyhow!("Quadlet ディレクトリを解決できません（HOME 未設定）"))?;

    sync_quadlet_dir(&dir, &config.name, stage_name, &units)?;
    systemctl_user_daemon_reload()?;

    let mut services_started = Vec::new();
    for unit in service_units(config, stage_name, stage) {
        systemctl_user_start(&unit)?;
        services_started.push(unit);
    }

    Ok(QuadletApplyOutcome {
        units_written: units.len(),
        services_started,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use fleetflow_core::{HealthCheck, Port, Volume};

    fn base_service() -> Service {
        Service {
            image: Some("docker.io/library/postgres:16".to_string()),
            ..Service::default()
        }
    }

    #[test]
    fn unit_naming_follows_project_stage_service() {
        assert_eq!(unit_base_name("myapp", "live", "db"), "myapp-live-db");
        assert_eq!(
            container_file_name("myapp", "live", "db"),
            "myapp-live-db.container"
        );
        assert_eq!(network_file_name("myapp", "live"), "myapp-live.network");
    }

    #[test]
    fn systemd_restart_maps_unless_stopped_to_always() {
        // systemd に unless-stopped は無いので always に寄せる
        assert_eq!(systemd_restart(RestartPolicy::UnlessStopped), "always");
        assert_eq!(systemd_restart(RestartPolicy::Always), "always");
        assert_eq!(systemd_restart(RestartPolicy::OnFailure), "on-failure");
        assert_eq!(systemd_restart(RestartPolicy::No), "no");
    }

    #[test]
    fn health_cmd_unwraps_cmd_shell_and_cmd() {
        assert_eq!(
            health_cmd(&["CMD-SHELL".into(), "curl -f localhost".into()]),
            Some("curl -f localhost".to_string())
        );
        assert_eq!(
            health_cmd(&["CMD".into(), "curl".into(), "-f".into(), "url".into()]),
            Some("curl -f url".to_string())
        );
        assert_eq!(health_cmd(&[]), None);
    }

    #[test]
    fn container_unit_has_required_sections_and_labels() {
        let unit = generate_container_unit("myapp", "live", "db", &base_service(), &[]);
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("[Container]"));
        assert!(unit.contains("[Service]"));
        assert!(unit.contains("[Install]"));
        assert!(unit.contains("ContainerName=myapp-live-db"));
        assert!(unit.contains("Image=docker.io/library/postgres:16"));
        assert!(unit.contains("Network=myapp-live.network"));
        // attribution label — observability が依存
        assert!(unit.contains("Label=fleetflow.project=myapp"));
        assert!(unit.contains("Label=fleetflow.stage=live"));
        assert!(unit.contains("Label=fleetflow.service=db"));
        assert!(unit.contains("WantedBy=default.target"));
    }

    #[test]
    fn container_unit_renders_ports_with_protocol() {
        let mut svc = base_service();
        svc.ports = vec![
            Port {
                host: 8080,
                container: 80,
                protocol: Protocol::Tcp,
                host_ip: None,
            },
            Port {
                host: 53,
                container: 53,
                protocol: Protocol::Udp,
                host_ip: Some("127.0.0.1".to_string()),
            },
        ];
        let unit = generate_container_unit("myapp", "live", "web", &svc, &[]);
        assert!(unit.contains("PublishPort=8080:80\n"));
        assert!(unit.contains("PublishPort=127.0.0.1:53:53/udp\n"));
    }

    #[test]
    fn container_unit_renders_env_volume_command() {
        let mut svc = base_service();
        svc.environment
            .insert("NODE_ENV".into(), "production".into());
        svc.environment.insert("PORT".into(), "3000".into());
        svc.volumes = vec![Volume {
            host: "./data".into(),
            container: "/data".into(),
            read_only: true,
        }];
        svc.command = Some("npm start".into());
        let unit = generate_container_unit("myapp", "live", "api", &svc, &[]);
        // env はキー順にソートされる（決定的出力）
        let port_idx = unit.find("Environment=PORT=3000").unwrap();
        let node_idx = unit.find("Environment=NODE_ENV=production").unwrap();
        assert!(node_idx < port_idx, "env はキー昇順");
        assert!(unit.contains("Volume=./data:/data:ro\n"));
        assert!(unit.contains("Exec=npm start\n"));
    }

    #[test]
    fn container_unit_renders_depends_on_as_systemd_ordering() {
        let unit = generate_container_unit(
            "myapp",
            "live",
            "api",
            &base_service(),
            &["db".to_string(), "redis".to_string()],
        );
        assert!(unit.contains("After=myapp-live-db.service"));
        assert!(unit.contains("Requires=myapp-live-db.service"));
        assert!(unit.contains("After=myapp-live-redis.service"));
    }

    #[test]
    fn container_unit_renders_healthcheck() {
        let mut svc = base_service();
        svc.healthcheck = Some(HealthCheck {
            test: vec!["CMD-SHELL".into(), "pg_isready".into()],
            interval: 30,
            timeout: 3,
            retries: 5,
            start_period: 10,
        });
        let unit = generate_container_unit("myapp", "live", "db", &svc, &[]);
        assert!(unit.contains("HealthCmd=pg_isready\n"));
        assert!(unit.contains("HealthInterval=30s\n"));
        assert!(unit.contains("HealthRetries=5\n"));
    }

    #[test]
    fn network_unit_has_network_section() {
        let unit = generate_network_unit("myapp", "live");
        assert!(unit.contains("[Network]"));
        assert!(unit.contains("NetworkName=myapp-live"));
        assert!(unit.contains("Label=fleetflow.project=myapp"));
    }

    // ── 適用層（WS2 Stage 2b）──

    #[test]
    fn is_fleetflow_unit_matches_own_project_stage_only() {
        // 自 project/stage の .container / .network は true
        assert!(is_fleetflow_unit(
            "myapp-live-db.container",
            "myapp",
            "live"
        ));
        assert!(is_fleetflow_unit(
            "myapp-live-web.container",
            "myapp",
            "live"
        ));
        assert!(is_fleetflow_unit("myapp-live.network", "myapp", "live"));
        // 別 stage / 別 project は false
        assert!(!is_fleetflow_unit(
            "myapp-dev-db.container",
            "myapp",
            "live"
        ));
        assert!(!is_fleetflow_unit(
            "other-live-db.container",
            "myapp",
            "live"
        ));
        assert!(!is_fleetflow_unit("myapp-dev.network", "myapp", "live"));
        // ユーザー手書きファイルは false
        assert!(!is_fleetflow_unit(
            "my-hand-written.container",
            "myapp",
            "live"
        ));
    }

    #[test]
    fn sync_quadlet_dir_writes_units() {
        let dir = tempfile::tempdir().unwrap();
        let units = vec![
            QuadletUnit {
                file_name: "myapp-live-db.container".to_string(),
                content: "[Container]\nImage=postgres\n".to_string(),
            },
            QuadletUnit {
                file_name: "myapp-live.network".to_string(),
                content: "[Network]\n".to_string(),
            },
        ];
        sync_quadlet_dir(dir.path(), "myapp", "live", &units).unwrap();

        assert_eq!(
            std::fs::read_to_string(dir.path().join("myapp-live-db.container")).unwrap(),
            "[Container]\nImage=postgres\n"
        );
        assert!(dir.path().join("myapp-live.network").exists());
    }

    #[test]
    fn sync_quadlet_dir_replaces_stale_units_keeps_others() {
        let dir = tempfile::tempdir().unwrap();

        // 初回: db + web の 2 service
        sync_quadlet_dir(
            dir.path(),
            "myapp",
            "live",
            &[
                QuadletUnit {
                    file_name: "myapp-live-db.container".into(),
                    content: "db".into(),
                },
                QuadletUnit {
                    file_name: "myapp-live-web.container".into(),
                    content: "web".into(),
                },
            ],
        )
        .unwrap();

        // 別 project/stage のファイルとユーザー手書きファイルを同ディレクトリに置く
        std::fs::write(dir.path().join("other-dev-x.container"), "other").unwrap();
        std::fs::write(dir.path().join("hand-written.container"), "manual").unwrap();

        // 2 回目: web を削除（db のみ）→ snapshot 置換
        sync_quadlet_dir(
            dir.path(),
            "myapp",
            "live",
            &[QuadletUnit {
                file_name: "myapp-live-db.container".into(),
                content: "db-v2".into(),
            }],
        )
        .unwrap();

        // db は更新、web は削除される（KDL から消えた service）
        assert_eq!(
            std::fs::read_to_string(dir.path().join("myapp-live-db.container")).unwrap(),
            "db-v2"
        );
        assert!(!dir.path().join("myapp-live-web.container").exists());
        // 別 project/stage・手書きファイルは touch されない
        assert!(dir.path().join("other-dev-x.container").exists());
        assert!(dir.path().join("hand-written.container").exists());
    }

    #[test]
    fn sync_quadlet_dir_creates_missing_directory() {
        let base = tempfile::tempdir().unwrap();
        let nested = base.path().join("containers/systemd");
        assert!(!nested.exists());
        sync_quadlet_dir(&nested, "myapp", "live", &[]).unwrap();
        assert!(nested.exists());
    }

    // ── ステージ適用（WS2 Stage 2c / WS3）──

    fn flow_with(
        services: Vec<(&str, Service)>,
        stage_services: Vec<&str>,
    ) -> (fleetflow_core::Flow, fleetflow_core::Stage) {
        let mut svc_map = std::collections::HashMap::new();
        for (name, svc) in services {
            svc_map.insert(name.to_string(), svc);
        }
        let stage = fleetflow_core::Stage {
            services: stage_services.iter().map(|s| s.to_string()).collect(),
            ..Default::default()
        };
        let mut stages = std::collections::HashMap::new();
        stages.insert("live".to_string(), stage.clone());
        let flow = fleetflow_core::Flow {
            name: "myapp".to_string(),
            services: svc_map,
            stages,
            providers: std::collections::HashMap::new(),
            servers: std::collections::HashMap::new(),
            registry: None,
            variables: std::collections::HashMap::new(),
            tenant: None,
        };
        (flow, stage)
    }

    fn container_service() -> Service {
        Service {
            image: Some("postgres:16".to_string()),
            ..Service::default()
        }
    }

    #[test]
    fn build_stage_units_emits_network_plus_containers() {
        let (flow, stage) = flow_with(
            vec![("db", container_service()), ("web", container_service())],
            vec!["db", "web"],
        );
        let units = build_stage_units(&flow, "live", &stage).unwrap();
        assert_eq!(units.len(), 3); // network 1 + container 2
        let names: Vec<&str> = units.iter().map(|u| u.file_name.as_str()).collect();
        assert!(names.contains(&"myapp-live.network"));
        assert!(names.contains(&"myapp-live-db.container"));
        assert!(names.contains(&"myapp-live-web.container"));
    }

    #[test]
    fn build_stage_units_skips_static_services() {
        let static_svc = Service {
            service_type: Some(fleetflow_core::ServiceType::Static),
            ..Service::default()
        };
        let (flow, stage) = flow_with(
            vec![("db", container_service()), ("site", static_svc)],
            vec!["db", "site"],
        );
        let units = build_stage_units(&flow, "live", &stage).unwrap();
        assert_eq!(units.len(), 2); // network 1 + container 1（static 除外）
        let names: Vec<&str> = units.iter().map(|u| u.file_name.as_str()).collect();
        assert!(!names.contains(&"myapp-live-site.container"));
    }

    #[test]
    fn build_stage_units_errors_on_missing_image() {
        let (flow, stage) = flow_with(vec![("db", Service::default())], vec!["db"]);
        assert!(build_stage_units(&flow, "live", &stage).is_err());
    }

    #[test]
    fn service_units_returns_systemd_service_names() {
        let (flow, stage) = flow_with(vec![("db", container_service())], vec!["db"]);
        assert_eq!(
            service_units(&flow, "live", &stage),
            vec!["myapp-live-db.service"]
        );
    }
}
