#!/usr/bin/env bash
# install-idle-shutdown.sh ジェネレータ
#
# scripts/idle-shutdown.{sh,service,timer} を inline 埋め込みで合成し、
# scripts/install-idle-shutdown.sh として書き出す。
#
# 必須: idle-shutdown.{sh,service,timer} の編集後にこれを実行して
#       install-idle-shutdown.sh を再生成、3 ファイル間の DRY を保証。
#
# 使い方:
#   bash scripts/build-install-idle-shutdown.sh
#
# CI で sync 確認するには:
#   bash scripts/build-install-idle-shutdown.sh && git diff --exit-code scripts/install-idle-shutdown.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"

OUT="scripts/install-idle-shutdown.sh"

cat > "${OUT}" <<'EOF_HEAD'
#!/usr/bin/env bash
# Install idle-shutdown timer on a worker host (self-contained)
#
# 使い方:
#   ssh root@<host> 'bash -s' < scripts/install-idle-shutdown.sh
#
# 冪等性: 既存 install を上書き + restart。
# Disable: touch /run/idle-shutdown.disable (一時)
#          systemctl disable --now idle-shutdown.timer (永続)
#
# !!! このファイルは生成物 !!!
# scripts/build-install-idle-shutdown.sh から生成。
# 直接編集せず、source ファイル (idle-shutdown.{sh,service,timer}) を編集してから
# bash scripts/build-install-idle-shutdown.sh で再生成してください。

set -euo pipefail

# Root が必須 (systemd unit / /usr/local/bin への書き込み)
if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "error: must run as root (sudo or root login)" >&2
  exit 1
fi

echo "=== idle-shutdown install ==="
echo "  host: $(hostname)"
echo "  date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

# 1. /usr/local/bin/idle-shutdown.sh
cat > /usr/local/bin/idle-shutdown.sh <<'SCRIPT_INNER'
EOF_HEAD

cat scripts/idle-shutdown.sh >> "${OUT}"

cat >> "${OUT}" <<'EOF_MID1'
SCRIPT_INNER
chmod +x /usr/local/bin/idle-shutdown.sh
echo "[1/4] /usr/local/bin/idle-shutdown.sh installed"

# 2. /etc/systemd/system/idle-shutdown.service
cat > /etc/systemd/system/idle-shutdown.service <<'SERVICE_INNER'
EOF_MID1

cat scripts/idle-shutdown.service >> "${OUT}"

cat >> "${OUT}" <<'EOF_MID2'
SERVICE_INNER
echo "[2/4] /etc/systemd/system/idle-shutdown.service installed"

# 3. /etc/systemd/system/idle-shutdown.timer
cat > /etc/systemd/system/idle-shutdown.timer <<'TIMER_INNER'
EOF_MID2

cat scripts/idle-shutdown.timer >> "${OUT}"

cat >> "${OUT}" <<'EOF_TAIL'
TIMER_INNER
echo "[3/5] /etc/systemd/system/idle-shutdown.timer installed"

# 4. /etc/default/idle-shutdown — caller 側 env を systemd EnvironmentFile に永続化
# spawn-build-worker.sh --idle-min N は install 時に IDLE_THRESHOLD_MIN env で
# 渡してくる (bash -s で receive)。 baked default ではなく caller 値を service
# 起動時に resolve させるため、 /etc/default/idle-shutdown に書き出す
# (idle-shutdown.service が EnvironmentFile=- で読む)。
#
# 未指定時は変数を空のまま書き、 idle-shutdown.sh の `${VAR:-default}` で fallback。
cat > /etc/default/idle-shutdown <<DEFAULT_INNER
# Generated by install-idle-shutdown.sh — do not edit manually.
# 再設定するには install-idle-shutdown.sh を env 付きで再実行。
IDLE_THRESHOLD_MIN=${IDLE_THRESHOLD_MIN:-}
MIN_UPTIME_MIN=${MIN_UPTIME_MIN:-}
GRACE_MIN=${GRACE_MIN:-}
DEFAULT_INNER
chmod 0644 /etc/default/idle-shutdown
echo "[4/5] /etc/default/idle-shutdown installed (IDLE_THRESHOLD_MIN=${IDLE_THRESHOLD_MIN:-<default>}, MIN_UPTIME_MIN=${MIN_UPTIME_MIN:-<default>}, GRACE_MIN=${GRACE_MIN:-<default>})"

# 5. systemd daemon-reload + enable + start
systemctl daemon-reload
systemctl enable --now idle-shutdown.timer
echo "[5/5] timer enabled & started"

echo ""
echo "=== status ==="
systemctl list-timers idle-shutdown.timer --no-pager 2>&1 | head -5
echo ""
echo "=== controls ==="
echo "  一時 disable: touch /run/idle-shutdown.disable"
echo "  永続 disable: systemctl disable --now idle-shutdown.timer"
echo "  shutdown cancel: shutdown -c"
echo "  log: journalctl -u idle-shutdown -n 20"
EOF_TAIL

chmod +x "${OUT}"
echo "✓ Generated ${OUT} ($(wc -l < ${OUT}) lines)"
